package com.markovic.javazadanie.model;

public enum ActivityAction {
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,

    RESOURCE_UPLOADED,
    RESOURCE_UPDATED,
    RESOURCE_DELETED,

    SUBMISSION_CREATED,
    SUBMISSION_GRADED,
    SUBMISSION_DELETED,

    COMMENT_CREATED,
    COMMENT_DELETED,

    USER_REGISTERED,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED
}
